version: '3.3'
services:
    obd-to-mqtt-homeassistant:
        container_name: obd-to-mqtt-homeassistant
        devices:
            - '/dev/rfcomm0:/dev/rfcomm0' #may need replacing if different device
        volumes:
            - './config:/usr/src/app/config'
        build: .
        restart: always 